version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: tilapia
      POSTGRES_USER: tilapia
      POSTGRES_DB: tilapia
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      PORT: 4000
      NODE_ENV: production
      JWT_SECRET: change-me-please
      ADMIN_EMAIL: admin@heroent.local
      ADMIN_PASSWORD: admin123
      DATABASE_URL: postgresql://tilapia:tilapia@postgres:5432/tilapia
      CORS_ORIGIN: http://localhost:8080,http://localhost:5173,http://localhost:5500
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

  adminer:
    image: adminer:4
    depends_on:
      - postgres
    ports:
      - "8081:8080"

volumes:
  db_data:
